#!/bin/bash

compile_run_java() {
    if [ -z "$1" ]; then
        echo "Uso: compile_run_java <nombre_del_archivo_sin_extension>"
        return 1
    fi

    local filename="$1"
    if [[ "$filename" == *.java ]]; then
        filename="${filename%.java}"
    fi

    javac "${filename}.java"
    compile_status=$?

    end_time=$(date +%s)

    if [ $compile_status -eq 0 ]; then
        echo "====================="
        java "${filename}"
        execution_status=$?

        if [ $execution_status -ne 0 ]; then
            echo "Error: La ejecución falló."
            return 1
        fi

        rm *.class
    else
        echo "Error: La compilación falló."
        return 1
    fi
}

compile_run_java "$1"
